// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreProject.PerformanceAPI.Data;

#nullable disable

namespace TheatreProject.PerformanceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250107052817_UpdateData")]
    partial class UpdateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheatreProject.PerformanceAPI.Models.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TheatreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3082ec5-ca83-4f70-bd14-47348b2df104"),
                            Address = "123 Theatre St",
                            AvailableSeats = 500,
                            BasePrice = 50.00m,
                            Capacity = 500,
                            Category = 1,
                            City = "London",
                            CreatedDate = new DateTime(2025, 1, 7, 5, 28, 16, 959, DateTimeKind.Utc).AddTicks(6745),
                            Description = "Shakespeare's classic tragedy of star-crossed lovers",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Romeo%20and%20Juliet.jpg",
                            Name = "Romeo and Juliet",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 14, 7, 28, 16, 959, DateTimeKind.Local).AddTicks(6701),
                            Status = 1,
                            TheatreName = "Royal Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("4ffc6461-b99f-42c0-bf64-36ca976803c3"),
                            Address = "1 Theatre Square",
                            AvailableSeats = 800,
                            BasePrice = 75.00m,
                            Capacity = 800,
                            Category = 4,
                            City = "Moscow",
                            CreatedDate = new DateTime(2025, 1, 7, 5, 28, 16, 959, DateTimeKind.Utc).AddTicks(6752),
                            Description = "Classic ballet by Tchaikovsky",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Swan%20Lake.jpg",
                            Name = "Swan Lake",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 21, 7, 28, 16, 959, DateTimeKind.Local).AddTicks(6749),
                            Status = 1,
                            TheatreName = "Bolshoi Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("d09955b1-6a72-41b6-a079-b64e8ebd8f93"),
                            Address = "1681 Broadway",
                            AvailableSeats = 600,
                            BasePrice = 100.00m,
                            Capacity = 600,
                            Category = 2,
                            City = "New York",
                            CreatedDate = new DateTime(2025, 1, 7, 5, 28, 16, 959, DateTimeKind.Utc).AddTicks(6757),
                            Description = "Andrew Lloyd Webber's masterpiece",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Phantom%20of%20the%20Opera.jpg",
                            Name = "The Phantom of the Opera",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 12, 7, 28, 16, 959, DateTimeKind.Local).AddTicks(6755),
                            Status = 1,
                            TheatreName = "Broadway Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("3fa637e4-7bd2-4886-9647-918d79d9c488"),
                            Address = "21 New Globe Walk",
                            AvailableSeats = 400,
                            BasePrice = 40.00m,
                            Capacity = 400,
                            Category = 3,
                            City = "London",
                            CreatedDate = new DateTime(2025, 1, 7, 5, 28, 16, 959, DateTimeKind.Utc).AddTicks(6762),
                            Description = "Shakespeare's shortest and most farcical comedy",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Comedy%20of%20Errors.jpg",
                            Name = "The Comedy of Errors",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 17, 7, 28, 16, 959, DateTimeKind.Local).AddTicks(6760),
                            Status = 1,
                            TheatreName = "Globe Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("31dbbf3b-aab3-4716-aaba-9638ac93cf09"),
                            Address = "Via Filodrammatici 2",
                            AvailableSeats = 700,
                            BasePrice = 85.00m,
                            Capacity = 700,
                            Category = 5,
                            City = "Milan",
                            CreatedDate = new DateTime(2025, 1, 7, 5, 28, 16, 959, DateTimeKind.Utc).AddTicks(6766),
                            Description = "Verdi's beloved opera",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/La%20Traviata.jpg",
                            Name = "La Traviata",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 28, 7, 28, 16, 959, DateTimeKind.Local).AddTicks(6764),
                            Status = 1,
                            TheatreName = "Teatro alla Scala",
                            TotalBookings = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
