// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreProject.PerformanceAPI.Data;

#nullable disable

namespace TheatreProject.PerformanceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250103050419_UpdateImageUrl")]
    partial class UpdateImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheatreProject.PerformanceAPI.Models.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TheatreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ee4f871-3991-4fe9-865b-84775d279e6f"),
                            Address = "123 Theatre St",
                            AvailableSeats = 500,
                            BasePrice = 50.00m,
                            Capacity = 500,
                            Category = 1,
                            City = "London",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's classic tragedy of star-crossed lovers",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Romeo%20and%20Juliet.jpg",
                            Name = "Romeo and Juliet",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 10, 7, 4, 18, 570, DateTimeKind.Local).AddTicks(4032),
                            Status = 0,
                            TheatreName = "Royal Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("f75267a6-e98f-4cca-8cb9-d53d5963139d"),
                            Address = "1 Theatre Square",
                            AvailableSeats = 800,
                            BasePrice = 75.00m,
                            Capacity = 800,
                            Category = 4,
                            City = "Moscow",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic ballet by Tchaikovsky",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Swan%20Lake.jpg",
                            Name = "Swan Lake",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 17, 7, 4, 18, 570, DateTimeKind.Local).AddTicks(4101),
                            Status = 0,
                            TheatreName = "Bolshoi Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("580aae4c-9458-410a-9151-f9c49dccf353"),
                            Address = "1681 Broadway",
                            AvailableSeats = 600,
                            BasePrice = 100.00m,
                            Capacity = 600,
                            Category = 2,
                            City = "New York",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Andrew Lloyd Webber's masterpiece",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Phantom%20of%20the%20Opera.jpg",
                            Name = "The Phantom of the Opera",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 8, 7, 4, 18, 570, DateTimeKind.Local).AddTicks(4109),
                            Status = 0,
                            TheatreName = "Broadway Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("55111aa7-bd3d-47ba-827f-c05c2919fdbe"),
                            Address = "21 New Globe Walk",
                            AvailableSeats = 400,
                            BasePrice = 40.00m,
                            Capacity = 400,
                            Category = 3,
                            City = "London",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's shortest and most farcical comedy",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Comedy%20of%20Errors.jpg",
                            Name = "The Comedy of Errors",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 13, 7, 4, 18, 570, DateTimeKind.Local).AddTicks(4116),
                            Status = 0,
                            TheatreName = "Globe Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("7f9771fa-1849-41dd-ad23-35846fad003f"),
                            Address = "Via Filodrammatici 2",
                            AvailableSeats = 700,
                            BasePrice = 85.00m,
                            Capacity = 700,
                            Category = 5,
                            City = "Milan",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Verdi's beloved opera",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/La%20Traviata.jpg",
                            Name = "La Traviata",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 24, 7, 4, 18, 570, DateTimeKind.Local).AddTicks(4122),
                            Status = 0,
                            TheatreName = "Teatro alla Scala",
                            TotalBookings = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
