// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreProject.PerformanceAPI.Data;

#nullable disable

namespace TheatreProject.PerformanceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheatreProject.PerformanceAPI.Models.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TheatreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("924022ee-1271-4426-93f6-fd0f4ac416b0"),
                            Address = "123 Theatre St",
                            AvailableSeats = 500,
                            BasePrice = 50.00m,
                            Capacity = 500,
                            Category = 1,
                            City = "London",
                            CreatedDate = new DateTime(2025, 1, 3, 8, 18, 46, 325, DateTimeKind.Utc).AddTicks(1187),
                            Description = "Shakespeare's classic tragedy of star-crossed lovers",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Romeo%20and%20Juliet.jpg",
                            Name = "Romeo and Juliet",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 10, 10, 18, 46, 325, DateTimeKind.Local).AddTicks(1124),
                            Status = 1,
                            TheatreName = "Royal Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("4d72afb2-39d0-402b-a60d-34a973f69e67"),
                            Address = "1 Theatre Square",
                            AvailableSeats = 800,
                            BasePrice = 75.00m,
                            Capacity = 800,
                            Category = 4,
                            City = "Moscow",
                            CreatedDate = new DateTime(2025, 1, 3, 8, 18, 46, 325, DateTimeKind.Utc).AddTicks(1199),
                            Description = "Classic ballet by Tchaikovsky",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/Swan%20Lake.jpg",
                            Name = "Swan Lake",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 17, 10, 18, 46, 325, DateTimeKind.Local).AddTicks(1195),
                            Status = 1,
                            TheatreName = "Bolshoi Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("5bb14b45-7b9e-4c10-9e26-f41e01caef0e"),
                            Address = "1681 Broadway",
                            AvailableSeats = 600,
                            BasePrice = 100.00m,
                            Capacity = 600,
                            Category = 2,
                            City = "New York",
                            CreatedDate = new DateTime(2025, 1, 3, 8, 18, 46, 325, DateTimeKind.Utc).AddTicks(1208),
                            Description = "Andrew Lloyd Webber's masterpiece",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Phantom%20of%20the%20Opera.jpg",
                            Name = "The Phantom of the Opera",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 8, 10, 18, 46, 325, DateTimeKind.Local).AddTicks(1204),
                            Status = 1,
                            TheatreName = "Broadway Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("41bc59f7-26b4-416e-9f88-33e5f704f265"),
                            Address = "21 New Globe Walk",
                            AvailableSeats = 400,
                            BasePrice = 40.00m,
                            Capacity = 400,
                            Category = 3,
                            City = "London",
                            CreatedDate = new DateTime(2025, 1, 3, 8, 18, 46, 325, DateTimeKind.Utc).AddTicks(1215),
                            Description = "Shakespeare's shortest and most farcical comedy",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/The%20Comedy%20of%20Errors.jpg",
                            Name = "The Comedy of Errors",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 13, 10, 18, 46, 325, DateTimeKind.Local).AddTicks(1212),
                            Status = 1,
                            TheatreName = "Globe Theatre",
                            TotalBookings = 0
                        },
                        new
                        {
                            Id = new Guid("c06da8a7-cd6e-4d8c-bf91-1a79d6d18d95"),
                            Address = "Via Filodrammatici 2",
                            AvailableSeats = 700,
                            BasePrice = 85.00m,
                            Capacity = 700,
                            Category = 5,
                            City = "Milan",
                            CreatedDate = new DateTime(2025, 1, 3, 8, 18, 46, 325, DateTimeKind.Utc).AddTicks(1223),
                            Description = "Verdi's beloved opera",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ImageUrl = "https://azurestorage90bh.blob.core.windows.net/theatre/La%20Traviata.jpg",
                            Name = "La Traviata",
                            Revenue = 0m,
                            ShowDateTime = new DateTime(2025, 1, 24, 10, 18, 46, 325, DateTimeKind.Local).AddTicks(1219),
                            Status = 1,
                            TheatreName = "Teatro alla Scala",
                            TotalBookings = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
