// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreProject.CouponAPI.Data;

#nullable disable

namespace TheatreProject.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120071519_AddedFixes")]
    partial class AddedFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheatreProject.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4349836-e348-41b0-ac7d-10c81cd1de0f"),
                            CouponCode = "NEW10",
                            DiscountAmount = 10m
                        },
                        new
                        {
                            Id = new Guid("bec4dda0-ed19-4da3-b7b1-2832c23e31a4"),
                            CouponCode = "EARLY20",
                            DiscountAmount = 20m
                        },
                        new
                        {
                            Id = new Guid("744d1a06-9109-48f9-89c6-aecc436b87b0"),
                            CouponCode = "GROUP15",
                            DiscountAmount = 15m
                        },
                        new
                        {
                            Id = new Guid("a6b216dc-724f-4da9-8e33-04dc2cd39e41"),
                            CouponCode = "VIP25",
                            DiscountAmount = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
