// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreProject.CouponAPI.Data;

#nullable disable

namespace TheatreProject.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheatreProject.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("daf81db8-7c80-415c-89dc-731c3074e06c"),
                            CouponCode = "NEW10",
                            DiscountAmount = 10.0
                        },
                        new
                        {
                            Id = new Guid("c4808c4d-c3c3-470d-93dd-4c097a8dc28e"),
                            CouponCode = "EARLY20",
                            DiscountAmount = 20.0
                        },
                        new
                        {
                            Id = new Guid("3d3b160d-e58a-4312-82bc-28f72e8e1684"),
                            CouponCode = "GROUP15",
                            DiscountAmount = 15.0
                        },
                        new
                        {
                            Id = new Guid("f0c479d5-58fc-4af3-acbf-46b04fe7ebc2"),
                            CouponCode = "VIP25",
                            DiscountAmount = 25.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
